apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: minicrit-prod

namespace: minicrit-prod

namePrefix: prod-

commonLabels:
  environment: production

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml
  - path: pdb-patch.yaml
  - path: ingress-patch.yaml

configMapGenerator:
  - name: minicrit-config
    behavior: merge
    literals:
      - LOG_LEVEL=WARNING
      - RATE_LIMIT_REQUESTS=50
