{{- if or .Values.secrets.huggingfaceToken .Values.secrets.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minicrit.fullname" . }}-secrets
  labels:
    {{- include "minicrit.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.huggingfaceToken }}
  HUGGINGFACE_TOKEN: {{ .Values.secrets.huggingfaceToken | quote }}
  {{- end }}
  {{- if .Values.secrets.apiKey }}
  API_KEY: {{ .Values.secrets.apiKey | quote }}
  {{- end }}
{{- end }}
