apiVersion: v1
kind: ServiceAccount
metadata:
  name: minicrit
  namespace: minicrit
  labels:
    app.kubernetes.io/name: minicrit
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
