apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minicrit
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
    - hosts:
        - minicrit-dev.example.com
      secretName: minicrit-dev-tls
  rules:
    - host: minicrit-dev.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minicrit
                port:
                  name: http
